version: "3.8"

services:
  ee_calculator:
    build: .
    container_name: ee_calculator_app
    volumes:
      - .:/app
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    container_name: ee_calculator_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: electrical_calculator
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./electrical_calculator.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
